/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as PortfolioConservationHeritageRouteImport } from './routes/portfolio/conservation-heritage'
import { Route as PortfolioPlanningApplicationsRouteImport } from './routes/portfolio/planning-applications'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesArchitecturalDesignRouteImport } from './routes/services/architectural-design'
import { Route as ServicesConservationHeritageRouteImport } from './routes/services/conservation-heritage'
import { Route as ServicesDesignConstructionRouteImport } from './routes/services/design-construction'
import { Route as ServicesInteriorDesignRouteImport } from './routes/services/interior-design'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioConservationHeritageRoute =
  PortfolioConservationHeritageRouteImport.update({
    id: '/portfolio/conservation-heritage',
    path: '/portfolio/conservation-heritage',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioPlanningApplicationsRoute =
  PortfolioPlanningApplicationsRouteImport.update({
    id: '/portfolio/planning-applications',
    path: '/portfolio/planning-applications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesArchitecturalDesignRoute =
  ServicesArchitecturalDesignRouteImport.update({
    id: '/services/architectural-design',
    path: '/services/architectural-design',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesConservationHeritageRoute =
  ServicesConservationHeritageRouteImport.update({
    id: '/services/conservation-heritage',
    path: '/services/conservation-heritage',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesDesignConstructionRoute =
  ServicesDesignConstructionRouteImport.update({
    id: '/services/design-construction',
    path: '/services/design-construction',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesInteriorDesignRoute = ServicesInteriorDesignRouteImport.update({
  id: '/services/interior-design',
  path: '/services/interior-design',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio/conservation-heritage': typeof PortfolioConservationHeritageRoute
  '/portfolio/planning-applications': typeof PortfolioPlanningApplicationsRoute
  '/services/architectural-design': typeof ServicesArchitecturalDesignRoute
  '/services/conservation-heritage': typeof ServicesConservationHeritageRoute
  '/services/design-construction': typeof ServicesDesignConstructionRoute
  '/services/interior-design': typeof ServicesInteriorDesignRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio/conservation-heritage': typeof PortfolioConservationHeritageRoute
  '/portfolio/planning-applications': typeof PortfolioPlanningApplicationsRoute
  '/services/architectural-design': typeof ServicesArchitecturalDesignRoute
  '/services/conservation-heritage': typeof ServicesConservationHeritageRoute
  '/services/design-construction': typeof ServicesDesignConstructionRoute
  '/services/interior-design': typeof ServicesInteriorDesignRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio/conservation-heritage': typeof PortfolioConservationHeritageRoute
  '/portfolio/planning-applications': typeof PortfolioPlanningApplicationsRoute
  '/services/architectural-design': typeof ServicesArchitecturalDesignRoute
  '/services/conservation-heritage': typeof ServicesConservationHeritageRoute
  '/services/design-construction': typeof ServicesDesignConstructionRoute
  '/services/interior-design': typeof ServicesInteriorDesignRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio/conservation-heritage'
    | '/portfolio/planning-applications'
    | '/services/architectural-design'
    | '/services/conservation-heritage'
    | '/services/design-construction'
    | '/services/interior-design'
    | '/portfolio/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio/conservation-heritage'
    | '/portfolio/planning-applications'
    | '/services/architectural-design'
    | '/services/conservation-heritage'
    | '/services/design-construction'
    | '/services/interior-design'
    | '/portfolio'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio/conservation-heritage'
    | '/portfolio/planning-applications'
    | '/services/architectural-design'
    | '/services/conservation-heritage'
    | '/services/design-construction'
    | '/services/interior-design'
    | '/portfolio/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PortfolioConservationHeritageRoute: typeof PortfolioConservationHeritageRoute
  PortfolioPlanningApplicationsRoute: typeof PortfolioPlanningApplicationsRoute
  ServicesArchitecturalDesignRoute: typeof ServicesArchitecturalDesignRoute
  ServicesConservationHeritageRoute: typeof ServicesConservationHeritageRoute
  ServicesDesignConstructionRoute: typeof ServicesDesignConstructionRoute
  ServicesInteriorDesignRoute: typeof ServicesInteriorDesignRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/conservation-heritage': {
      id: '/portfolio/conservation-heritage'
      path: '/portfolio/conservation-heritage'
      fullPath: '/portfolio/conservation-heritage'
      preLoaderRoute: typeof PortfolioConservationHeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/planning-applications': {
      id: '/portfolio/planning-applications'
      path: '/portfolio/planning-applications'
      fullPath: '/portfolio/planning-applications'
      preLoaderRoute: typeof PortfolioPlanningApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/architectural-design': {
      id: '/services/architectural-design'
      path: '/services/architectural-design'
      fullPath: '/services/architectural-design'
      preLoaderRoute: typeof ServicesArchitecturalDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/conservation-heritage': {
      id: '/services/conservation-heritage'
      path: '/services/conservation-heritage'
      fullPath: '/services/conservation-heritage'
      preLoaderRoute: typeof ServicesConservationHeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/design-construction': {
      id: '/services/design-construction'
      path: '/services/design-construction'
      fullPath: '/services/design-construction'
      preLoaderRoute: typeof ServicesDesignConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/interior-design': {
      id: '/services/interior-design'
      path: '/services/interior-design'
      fullPath: '/services/interior-design'
      preLoaderRoute: typeof ServicesInteriorDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PortfolioConservationHeritageRoute: PortfolioConservationHeritageRoute,
  PortfolioPlanningApplicationsRoute: PortfolioPlanningApplicationsRoute,
  ServicesArchitecturalDesignRoute: ServicesArchitecturalDesignRoute,
  ServicesConservationHeritageRoute: ServicesConservationHeritageRoute,
  ServicesDesignConstructionRoute: ServicesDesignConstructionRoute,
  ServicesInteriorDesignRoute: ServicesInteriorDesignRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
